<?php
			$optionsArray = array( 'welcome' => array( 'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'breadcrumb' => array( 'menutItem' => false ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_interno',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'vtik_interno',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_calendario',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_memorando',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_memorando_pend',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_memorando_aut',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_chat',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_tipomemo',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tik_memorando_aut_otrdep',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'SolicitudesVencidas',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'vtik_memorando_hist',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'above-grid' => array( 'breadcrumb' ),
'grid' => array( 'welcome_item1',
'welcome_item7',
'welcome_item3',
'welcome_item2',
'welcome_item12',
'welcome_item13',
'welcome_item11',
'welcome_item4',
'welcome_item',
'welcome_item5',
'welcome_item6' ) ),
'formXtTags' => array( 'above-grid' => array( 'breadcrumb' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'above-grid',
'welcome_item1' => 'grid',
'welcome_item7' => 'grid',
'welcome_item3' => 'grid',
'welcome_item2' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item11' => 'grid',
'welcome_item4' => 'grid',
'welcome_item' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'breadcrumb' => array( 'breadcrumb' ),
'welcome_item' => array( 'welcome_item1',
'welcome_item3',
'welcome_item7',
'welcome_item2',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item4',
'welcome_item',
'welcome_item5',
'welcome_item6' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item1',
'welcome_item7',
'welcome_item3',
'welcome_item2',
'welcome_item12',
'welcome_item13',
'welcome_item11',
'welcome_item4',
'welcome_item',
'welcome_item5',
'welcome_item6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tik_interno',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_interno',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'linkComments' => array( 'text' => '',
'type' => 0 ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tik_calendario',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_calendario',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'type' => 0,
'text' => '' ) ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vtik_interno',
'linkPage' => 'list',
'linkText' => array( 'table' => 'vtik_interno',
'type' => 6 ),
'background' => '#778899',
'linkComments' => array( 'type' => 0,
'text' => '' ),
'linkIcon' => array( 'glyph' => 'th-list' ) ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkTable' => 'tik_memorando',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_memorando',
'type' => 6 ) ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tik_chat',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_chat',
'type' => 6 ),
'background' => '#5F9EA0' ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkTable' => 'tik_memorando_pend',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_memorando_pend',
'type' => 6 ) ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkTable' => 'tik_memorando_aut',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_memorando_aut',
'type' => 6 ) ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tik_tipomemo',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_tipomemo',
'type' => 6 ),
'background' => '#008B8B' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tik_memorando_aut_otrdep',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tik_memorando_aut_otrdep',
'type' => 6 ),
'background' => '#4169E1' ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'SolicitudesVencidas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'SolicitudesVencidas',
'type' => 6 ),
'background' => '#4169E1' ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vtik_memorando_hist',
'linkPage' => 'list',
'linkText' => array( 'table' => 'vtik_memorando_hist',
'type' => 6 ),
'background' => '#9ACD32' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>