<?php
			$optionsArray = array( 'totals' => array( 'Solicitud' => array( 'totalsType' => '' ),
'Documento' => array( 'totalsType' => '' ),
'TipoSolicitud' => array( 'totalsType' => '' ),
'DepartamentoSolicitante' => array( 'totalsType' => '' ),
'UsuarioSolicitante' => array( 'totalsType' => '' ),
'DepartamentoSolicitar' => array( 'totalsType' => '' ),
'Asunto' => array( 'totalsType' => '' ),
'DescripcionAmplia' => array( 'totalsType' => '' ),
'FechaSolicitud' => array( 'totalsType' => '' ),
'FechaInicio' => array( 'totalsType' => '' ),
'UsuarioInicio' => array( 'totalsType' => '' ),
'FechaFinal' => array( 'totalsType' => '' ),
'Observaciones' => array( 'totalsType' => '' ),
'Evaluacion' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'FechaAtencion' => array( 'totalsType' => '' ),
'ProcesoAtencion' => array( 'totalsType' => '' ),
'FechaAtencionFinal' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Solicitud',
'DepartamentoSolicitante',
'UsuarioSolicitante',
'DepartamentoSolicitar',
'Asunto',
'DescripcionAmplia',
'FechaSolicitud',
'FechaInicio',
'UsuarioInicio',
'FechaFinal',
'Observaciones',
'Evaluacion',
'Estado',
'TipoSolicitud',
'Documento',
'FechaAtencion',
'ProcesoAtencion',
'FechaAtencionFinal' ),
'exportFields' => array( 'Solicitud',
'Documento',
'TipoSolicitud',
'DepartamentoSolicitante',
'UsuarioSolicitante',
'DepartamentoSolicitar',
'Asunto',
'DescripcionAmplia',
'FechaSolicitud',
'FechaInicio',
'UsuarioInicio',
'FechaFinal',
'Observaciones',
'Evaluacion',
'Estado',
'FechaAtencion',
'ProcesoAtencion',
'FechaAtencionFinal' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Solicitud' => array( 'export_field' ),
'DepartamentoSolicitante' => array( 'export_field2' ),
'UsuarioSolicitante' => array( 'export_field3' ),
'DepartamentoSolicitar' => array( 'export_field4' ),
'Asunto' => array( 'export_field5' ),
'DescripcionAmplia' => array( 'export_field6' ),
'FechaSolicitud' => array( 'export_field7' ),
'FechaInicio' => array( 'export_field8' ),
'UsuarioInicio' => array( 'export_field9' ),
'FechaFinal' => array( 'export_field10' ),
'Observaciones' => array( 'export_field11' ),
'Evaluacion' => array( 'export_field12' ),
'Estado' => array( 'export_field13' ),
'TipoSolicitud' => array( 'export_field14' ),
'Documento' => array( 'export_field1' ),
'FechaAtencion' => array( 'export_field15' ),
'ProcesoAtencion' => array( 'export_field16' ),
'FechaAtencionFinal' => array( 'export_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field14',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field15',
'export_field16',
'export_field17' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field14' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field1',
'export_field15',
'export_field16',
'export_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field14',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field15',
'export_field16',
'export_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Solicitud',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'DepartamentoSolicitante',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'UsuarioSolicitante',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'DepartamentoSolicitar',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Asunto',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'DescripcionAmplia',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'FechaSolicitud',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'FechaInicio',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'UsuarioInicio',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'FechaFinal',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Observaciones',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Evaluacion',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Estado',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'TipoSolicitud',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Documento',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'FechaAtencion',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'ProcesoAtencion',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'FechaAtencionFinal',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>