<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Usuario',
'FirmaDigital',
'Firma',
'ValidoHasta',
'Departamentos' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'Usuario' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field4' ),
'FirmaDigital' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field6' ),
'Firma' => array( 'integrated_edit_field2',
'integrated_edit_field7',
'integrated_edit_field8' ),
'ValidoHasta' => array( 'edit_field',
'edit_field_label',
'edit_field_tooltip' ),
'Departamentos' => array( 'edit_field1',
'edit_field_label1',
'edit_field_tooltip1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field1',
'custom_button',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field2',
'integrated_edit_field8',
'edit_field_label',
'edit_field',
'edit_field_tooltip',
'edit_field_label1',
'edit_field1',
'edit_field_tooltip1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field1' => 'grid',
'custom_button' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field8' => 'grid',
'edit_field_label' => 'grid',
'edit_field' => 'grid',
'edit_field_tooltip' => 'grid',
'edit_field_label1' => 'grid',
'edit_field1' => 'grid',
'edit_field_tooltip1' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'edit_field' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'edit_field1' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'edit_field_tooltip1' => array( 'location' => 'grid',
'cellId' => 'c15' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'edit_field',
'edit_field1' ),
'edit_field_label' => array( 'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field7',
'edit_field_label',
'edit_field_label1' ),
'edit_field_tooltip' => array( 'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field8',
'edit_field_tooltip',
'edit_field_tooltip1' ),
'custom_button' => array( 'custom_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Usuario_fieldblock' ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'FirmaDigital_fieldblock' ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'Firma_fieldblock' ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'ValidoHasta_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'Departamentos_fieldblock' ),
'items' => array( 'edit_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'genpin' ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'genpin' ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field3' ),
'field' => 'Usuario' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'field' => 'Usuario' ),
'c' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ),
'field' => 'Usuario' ),
'c5' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field5' ),
'field' => 'FirmaDigital' ),
'c3' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field1',
'custom_button' ),
'field' => 'FirmaDigital' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'field' => 'FirmaDigital' ),
'c7' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field7' ),
'field' => 'Firma' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field2' ),
'field' => 'Firma' ),
'c9' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field8' ),
'field' => 'Firma' ),
'c10' => array( 'model' => 'c4',
'items' => array( 'edit_field_label' ),
'field' => 'ValidoHasta' ),
'c11' => array( 'model' => 'c2',
'items' => array( 'edit_field' ),
'field' => 'ValidoHasta' ),
'c12' => array( 'model' => 'c2',
'items' => array( 'edit_field_tooltip' ),
'field' => 'ValidoHasta' ),
'c13' => array( 'model' => 'c4',
'items' => array( 'edit_field_label1' ),
'field' => 'Departamentos' ),
'c14' => array( 'model' => 'c2',
'items' => array( 'edit_field1' ),
'field' => 'Departamentos' ),
'c15' => array( 'model' => 'c2',
'items' => array( 'edit_field_tooltip1' ),
'field' => 'Departamentos' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field' => array( 'field' => 'Usuario',
'type' => 'edit_field',
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'FirmaDigital',
'type' => 'edit_field',
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'Firma',
'type' => 'edit_field' ),
'integrated_edit_field3' => array( 'type' => 'edit_field_label',
'field' => 'Usuario' ),
'integrated_edit_field4' => array( 'type' => 'edit_field_tooltip',
'field' => 'Usuario' ),
'integrated_edit_field5' => array( 'type' => 'edit_field_label',
'field' => 'FirmaDigital' ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'genpin',
'label' => array( 'text' => 'Generar',
'type' => 0 ) ),
'integrated_edit_field6' => array( 'type' => 'edit_field_tooltip',
'field' => 'FirmaDigital' ),
'integrated_edit_field7' => array( 'type' => 'edit_field_label',
'field' => 'Firma' ),
'integrated_edit_field8' => array( 'type' => 'edit_field_tooltip',
'field' => 'Firma' ),
'edit_field' => array( 'field' => 'ValidoHasta',
'type' => 'edit_field',
'updateOnEdit' => false ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'ValidoHasta' ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'ValidoHasta' ),
'edit_field1' => array( 'field' => 'Departamentos',
'type' => 'edit_field',
'updateOnEdit' => false ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'Departamentos' ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'Departamentos' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>