<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'tik_restulado' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ) ),
'totals' => array( 'Solicitud' => array( 'totalsType' => '' ),
'Documento' => array( 'totalsType' => '' ),
'TipoSolicitud' => array( 'totalsType' => '' ),
'DepartamentoSolicitante' => array( 'totalsType' => '' ),
'UsuarioSolicitante' => array( 'totalsType' => '' ),
'DepartamentoSolicitar' => array( 'totalsType' => '' ),
'Asunto' => array( 'totalsType' => '' ),
'DescripcionAmplia' => array( 'totalsType' => '' ),
'FechaSolicitud' => array( 'totalsType' => '' ),
'FechaInicio' => array( 'totalsType' => '' ),
'UsuarioInicio' => array( 'totalsType' => '' ),
'FechaFinal' => array( 'totalsType' => '' ),
'Observaciones' => array( 'totalsType' => '' ),
'Evaluacion' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'FechaAtencion' => array( 'totalsType' => '' ),
'ProcesoAtencion' => array( 'totalsType' => '' ),
'FechaExpiracion' => array( 'totalsType' => '' ),
'FechaMaxima' => array( 'totalsType' => '' ),
'FechaAtencionFinal' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Solicitud',
'DepartamentoSolicitante',
'UsuarioSolicitante',
'DepartamentoSolicitar',
'Asunto',
'DescripcionAmplia',
'FechaSolicitud',
'FechaInicio',
'UsuarioInicio',
'FechaFinal',
'Observaciones',
'Estado',
'TipoSolicitud',
'Documento',
'FechaAtencion',
'ProcesoAtencion',
'FechaAtencionFinal' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Solicitud' => array( 'simple_grid_field',
'simple_grid_field15' ),
'DepartamentoSolicitante' => array( 'simple_grid_field2',
'simple_grid_field17' ),
'UsuarioSolicitante' => array( 'simple_grid_field3',
'simple_grid_field18' ),
'DepartamentoSolicitar' => array( 'simple_grid_field4',
'simple_grid_field19' ),
'Asunto' => array( 'simple_grid_field5',
'simple_grid_field20' ),
'DescripcionAmplia' => array( 'simple_grid_field6',
'simple_grid_field21' ),
'FechaSolicitud' => array( 'simple_grid_field7',
'simple_grid_field22' ),
'FechaInicio' => array( 'simple_grid_field8',
'simple_grid_field23' ),
'UsuarioInicio' => array( 'simple_grid_field9',
'simple_grid_field24' ),
'FechaFinal' => array( 'simple_grid_field10',
'simple_grid_field25' ),
'Observaciones' => array( 'simple_grid_field11',
'simple_grid_field26' ),
'Estado' => array( 'simple_grid_field13',
'simple_grid_field28' ),
'TipoSolicitud' => array( 'simple_grid_field14',
'simple_grid_field29' ),
'Documento' => array( 'grid_field',
'grid_field_label' ),
'FechaAtencion' => array( 'grid_field1',
'grid_field_label1' ),
'ProcesoAtencion' => array( 'grid_field2',
'grid_field_label2' ),
'FechaAtencionFinal' => array( 'grid_field3',
'grid_field_label3' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field15',
'details_preview',
'details_preview1',
'simple_grid_field',
'simple_grid_field21',
'simple_grid_field6',
'simple_grid_field20',
'simple_grid_field5',
'simple_grid_field19',
'simple_grid_field4',
'simple_grid_field18',
'simple_grid_field3',
'simple_grid_field17',
'simple_grid_field2',
'simple_grid_field28',
'simple_grid_field13',
'simple_grid_field26',
'simple_grid_field11',
'simple_grid_field23',
'simple_grid_field8',
'simple_grid_field24',
'simple_grid_field9',
'simple_grid_field22',
'simple_grid_field7',
'simple_grid_field25',
'simple_grid_field10',
'simple_grid_field29',
'simple_grid_field14',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label3',
'grid_field3',
'grid_field_label2',
'grid_field2' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field15' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field14' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid' ),
'itemLocations' => array( 'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field56' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field57' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field70' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field71' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field84' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field85' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field98' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field99' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field112' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field113' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field140' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field141' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field142' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field143' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field154' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field155' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field156' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field157' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_field102' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field103' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_field104' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field105' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_field107' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field109' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field13',
'simple_grid_field14',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3' ),
'master_info' => array( 'master_info' ),
'details_preview' => array( 'details_preview',
'details_preview1' ),
'grid_field_label' => array( 'simple_grid_field15',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field28',
'simple_grid_field29',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Documento_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Documento_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'TipoSolicitud_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'TipoSolicitud_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'Solicitud_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'Solicitud_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field84' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'DepartamentoSolicitante_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field85' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 4 ),
'tags' => array( 'DepartamentoSolicitante_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field70' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'UsuarioSolicitante_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field71' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 5 ),
'tags' => array( 'UsuarioSolicitante_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field56' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'DepartamentoSolicitar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field57' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array( 'DepartamentoSolicitar_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'Asunto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 7 ),
'tags' => array( 'Asunto_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'DescripcionAmplia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array( 'DescripcionAmplia_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field154' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'FechaSolicitud_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field155' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'FechaSolicitud_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field156' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'FechaFinal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field157' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'FechaFinal_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field140' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'FechaInicio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field141' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'FechaInicio_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field142' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array( 'UsuarioInicio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field143' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'UsuarioInicio_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field112' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'Observaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field113' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 11 ),
'tags' => array( 'Observaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field102' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'FechaAtencion_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field103' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'FechaAtencion_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field104' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array( 'FechaAtencionFinal_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field105' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array( 'FechaAtencionFinal_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field107' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'ProcesoAtencion_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field109' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'ProcesoAtencion_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field110' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field111' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field98' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array( 'Estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field99' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array( 'Estado_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field100' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field101' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0,
1 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 17 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field84' ),
array( 'cell' => 'cell_field85',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field70' ),
array( 'cell' => 'cell_field71',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field56' ),
array( 'cell' => 'cell_field57',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field154' ),
array( 'cell' => 'cell_field155' ),
array( 'cell' => 'cell_field156' ),
array( 'cell' => 'cell_field157' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field140' ),
array( 'cell' => 'cell_field141' ),
array( 'cell' => 'cell_field142' ),
array( 'cell' => 'cell_field143' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field112' ),
array( 'cell' => 'cell_field113',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field102' ),
array( 'cell' => 'cell_field103' ),
array( 'cell' => 'cell_field104' ),
array( 'cell' => 'cell_field105' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field107' ),
array( 'cell' => 'cell_field109' ),
array( 'cell' => 'cell_field110' ),
array( 'cell' => 'cell_field111' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field98' ),
array( 'cell' => 'cell_field99' ),
array( 'cell' => 'cell_field100' ),
array( 'cell' => 'cell_field101' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field',
'colspan' => 2 ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'Solicitud',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ),
'columnName' => '' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ),
'columnName' => '' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'columnName' => '' ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Solicitud',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'columnName' => 'field',
'field' => 'DescripcionAmplia' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'columnName' => 'field',
'field' => 'DescripcionAmplia' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'columnName' => 'field',
'field' => 'Asunto' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'columnName' => 'field',
'field' => 'Asunto' ),
'cell_field56' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'columnName' => 'field',
'field' => 'DepartamentoSolicitar' ),
'cell_field57' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'columnName' => 'field',
'field' => 'DepartamentoSolicitar' ),
'cell_field70' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'columnName' => 'field',
'field' => 'UsuarioSolicitante' ),
'cell_field71' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'columnName' => 'field',
'field' => 'UsuarioSolicitante' ),
'cell_field84' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'columnName' => 'field',
'field' => 'DepartamentoSolicitante' ),
'cell_field85' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'columnName' => 'field',
'field' => 'DepartamentoSolicitante' ),
'cell_field98' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'columnName' => 'field',
'field' => 'Estado' ),
'cell_field99' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'columnName' => 'field',
'field' => 'Estado' ),
'cell_field100' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field101' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field112' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'columnName' => 'field',
'field' => 'Observaciones' ),
'cell_field113' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'columnName' => 'field',
'field' => 'Observaciones' ),
'cell_field140' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'columnName' => 'field',
'field' => 'FechaInicio' ),
'cell_field141' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'columnName' => 'field',
'field' => 'FechaInicio' ),
'cell_field142' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'columnName' => 'field',
'field' => 'UsuarioInicio' ),
'cell_field143' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'columnName' => 'field',
'field' => 'UsuarioInicio' ),
'cell_field154' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'columnName' => 'field',
'field' => 'FechaSolicitud' ),
'cell_field155' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'columnName' => 'field',
'field' => 'FechaSolicitud' ),
'cell_field156' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'columnName' => 'field',
'field' => 'FechaFinal' ),
'cell_field157' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'columnName' => 'field',
'field' => 'FechaFinal' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'columnName' => 'field',
'field' => 'TipoSolicitud' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'columnName' => 'field',
'field' => 'TipoSolicitud' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label' ),
'columnName' => 'field',
'field' => 'Documento' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'columnName' => 'field',
'field' => 'Documento' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field102' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label1' ),
'columnName' => 'field',
'field' => 'FechaAtencion' ),
'cell_field103' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'columnName' => 'field',
'field' => 'FechaAtencion' ),
'cell_field104' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label3' ),
'columnName' => 'field',
'field' => 'FechaAtencionFinal' ),
'cell_field105' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'columnName' => 'field',
'field' => 'FechaAtencionFinal' ),
'cell_field107' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label2' ),
'columnName' => 'field',
'field' => 'ProcesoAtencion' ),
'cell_field109' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'columnName' => 'field',
'field' => 'ProcesoAtencion' ),
'cell_field110' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ),
'cell_field111' => array( 'model' => 'cell_field',
'items' => array(  ),
'columnName' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'Solicitud',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'DepartamentoSolicitante',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'UsuarioSolicitante',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'DepartamentoSolicitar',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'Asunto',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'DescripcionAmplia',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'field' => 'FechaSolicitud',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'FechaInicio',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'UsuarioInicio',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'FechaFinal',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'Observaciones',
'type' => 'grid_field' ),
'simple_grid_field13' => array( 'field' => 'Estado',
'type' => 'grid_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'tik_satisfaccion' => 'true' ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tik_documento',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tik_restulado',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'simple_grid_field14' => array( 'field' => 'TipoSolicitud',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'Solicitud' ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'DepartamentoSolicitante' ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'UsuarioSolicitante' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'DepartamentoSolicitar' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'Asunto' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'DescripcionAmplia' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'FechaSolicitud' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'FechaInicio' ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'UsuarioInicio' ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'FechaFinal' ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'Observaciones' ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'Estado' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'TipoSolicitud' ),
'grid_field' => array( 'field' => 'Documento',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Documento' ),
'grid_field1' => array( 'field' => 'FechaAtencion',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'FechaAtencion' ),
'grid_field2' => array( 'field' => 'ProcesoAtencion',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'ProcesoAtencion' ),
'grid_field3' => array( 'field' => 'FechaAtencionFinal',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'FechaAtencionFinal' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>