<?php
			$optionsArray = array( 'totals' => array( 'Usuario' => array( 'totalsType' => '' ),
'Clave' => array( 'totalsType' => '' ),
'Nombre' => array( 'totalsType' => '' ),
'CodigoDepto' => array( 'totalsType' => '' ),
'Puesto' => array( 'totalsType' => '' ),
'Codigo_Estructura' => array( 'totalsType' => '' ),
'Area' => array( 'totalsType' => '' ),
'Correo' => array( 'totalsType' => '' ),
'Telefono' => array( 'totalsType' => '' ),
'FechaInicio' => array( 'totalsType' => '' ),
'FechaFinal' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Usuario',
'Clave',
'Nombre',
'Puesto',
'Correo',
'FechaInicio',
'FechaFinal',
'Estado',
'CodigoDepto',
'Codigo_Estructura',
'Area',
'Telefono' ),
'exportFields' => array( 'Usuario',
'Clave',
'Nombre',
'Puesto',
'Correo',
'FechaInicio',
'FechaFinal',
'Estado',
'CodigoDepto',
'Codigo_Estructura',
'Area',
'Telefono' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Usuario' => array( 'export_field' ),
'Clave' => array( 'export_field1' ),
'Nombre' => array( 'export_field2' ),
'Puesto' => array( 'export_field4' ),
'Correo' => array( 'export_field5' ),
'FechaInicio' => array( 'export_field6' ),
'FechaFinal' => array( 'export_field7' ),
'Estado' => array( 'export_field8' ),
'CodigoDepto' => array( 'export_field9' ),
'Codigo_Estructura' => array( 'export_field3' ),
'Area' => array( 'export_field10' ),
'Telefono' => array( 'export_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field3',
'export_field10',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field3' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field3',
'export_field10',
'export_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field3',
'export_field10',
'export_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Usuario',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Clave',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Nombre',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Puesto',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Correo',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'FechaInicio',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'FechaFinal',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Estado',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'CodigoDepto',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Codigo_Estructura',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Area',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Telefono',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>