<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_asistencias_realizadas_por_fecha  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeQueryReport"]=true;

		$this->events["BeforeQueryReportPrint"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Report page: Before SQL query
function BeforeQueryReport(&$strWhereClause)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = "DepartamentoSolicitar = ".$_SESSION["CodigoDepto"];
;		
} // function BeforeQueryReport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Report Print page: Before SQL query
function BeforeQueryReportPrint(&$strWhereClause)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = "DepartamentoSolicitar = ".$_SESSION["CodigoDepto"];
;		
} // function BeforeQueryReportPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
