<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_gr_fico_de_asistencias  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeQueryChart"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Chart page: Before SQL query
function BeforeQueryChart(&$strSQL, &$strWhereClause, &$strOrderBy)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = "DepartamentoSolicitar = ".$_SESSION["CodigoDepto"];
;		
} // function BeforeQueryChart

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
