<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pendientes_por_departamento  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowReport"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowReport(&$xt, &$templatefile, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $data["Estado"]=="En Proceso" )
	$record["css"]='background:#70F2FF;';
if( $data["Estado"]=="Terminado" )
	$record["css"]='background:#F5EE6C;';
if( $data["Estado"]=="Evaluado" )
	$record["css"]='background:#AFD562;';

;		
} // function BeforeShowReport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
