<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tik_memorando_pend  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowView"]=true;

		$this->events["BeforeQueryList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
// Agregar registro de Lectura
$sqla = "insert ignore into tik_memorando_l (NoMemorando,A,FechaHora)";
$sqla .= " values(".$values['NoMemorando'].",'".$_SESSION["UserID"]."','".strftime("%Y-%m-%d %H:%M:%S")."')";
CustomQuery($sqla);

;		
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = "Todos=1 or FIND_IN_SET('".$_SESSION["UserID"]."',A) or FIND_IN_SET('".$_SESSION["CodigoDepto"]."',ADepartamento)";

;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
