<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tik_interno  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["ProcessValuesAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["BeforeDelete"]=true;

		$this->events["BeforeAdd"]=true;



		$this->events["BeforeQueryList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$values['DepartamentoSolicitante'] = $_SESSION['CodigoDepto'];

;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
// Habilitar o inhabilitar el link de edición
//var_dump($data['Estado']);
if( $data['Estado'] == 'En Proceso' || $data['Estado'] == 'Evaluado' ) {
	$record["edit_link"] = false;
}
if( $data["Estado"]=="En Proceso" )
	$record["css"]='background:#70F2FF;';
if( $data["Estado"]=="Terminado" )
	$record["css"]='background:#F5EE6C;';
if( $data["Estado"]=="Evaluado" )
	$record["css"]='background:#AFD562;';
//  Cambiar el llamado del link de edición (Revisarlo)
/* if( $data['Estado'] == 'Terminado' ) {
	$editlink=" editid1=".htmlspecialchars(rawurlencode($data["Solicitud"]));
	$record["editlink_attrs"]="href=\"tik_interno_edit1.php?".$editlink."\" ";
}  */

;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $values['Estado'] == 'Pendiente' ) {
	return true;
} else {
	if( $values['Estado'] == 'Terminado' && $values['Evaluacion'] > 0 ) {
		$values['Estado'] = 'Evaluado';
		return true;
	} else {
		$message = "Debe evaluar para poder cerrar ficha.";
		return false;
	}
}
$values['Asunto'] = strtoupper($values['Asunto']);
$values['DescripcionAmplia'] = strtoupper($values['DescripcionAmplia']);

;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $deleted_values["Estado"] == 'Pendiente' ) {
	return true;
} else {
	$message = "No puede eliminar el ticket: En Proceso, Terminado o Evaluado...";
	return false;
}
;		
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( trim($values['Documento']) == '' ) {
	return false;
} else {
	$docto = trim($_SESSION["Codigo_Estructura"].'-'.$_SESSION["Area"].'-'.$values['Documento']);
	$sqlx = "SELECT tik_interno_autoinc('".$docto."') as nuevodoc";
	$rsx = CustomQuery($sqlx);
	if( $datax = db_fetch_array($rsx) ) {
		$values['Documento'] = $datax["nuevodoc"];
	} else {
		return false;
	}
}
$values['Asunto'] = strtoupper($values['Asunto']);
$values['DescripcionAmplia'] = strtoupper($values['DescripcionAmplia']);

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = "DepartamentoSolicitante = ".$_SESSION["CodigoDepto"];

;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
