<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tik_firmas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
// Guardar PIN anterior
$sqlb = "insert into tik_firmash (Usuario, FechaCambio, FirmaDigital, Firma)";
$sqlb .= " values('".$values['Usuario']."','".strftime("%Y-%m-%d")."','".$oldvalues['FirmaDigital']."','".$oldvalues['Firma']."')";
$sqlb .= " on duplicate key update FirmaDigital = '".$oldvalues['FirmaDigital']."', Firma = '".$oldvalues['Firma']."'";
CustomQuery($sqlb);

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
