<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_vtik_interno  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["ProcessValuesAdd"]=true;


		$this->events["ProcessValuesEdit"]=true;

		$this->events["BeforeMoveNextList"]=true;


		$this->events["BeforeQueryPrint"]=true;


		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $values['UsuarioSolicitante'] ) {
	$sql = 'select * from zusuarios where Usuario="'.$_SESSION["UserID"].'"';
	$rs = CustomQuery($sql);
	if( $data = db_fetch_array($rs) ) {
		$values['DepartamentoSolicitante'] = $data['CodigoDepto'];
	}
}

;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $values['Estado'] == 'Pendiente' ) {
	$values['FechaInicio'] = strftime("%Y-%m-%d %H:%M:%S");
	$values['UsuarioInicio'] = $_SESSION["UserID"];
} else if($values['Estado'] == 'En Proceso' ) {
	$values['FechaFinal'] = strftime("%Y-%m-%d %H:%M:%S");
}

;		
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $data["Estado"]=="Terminado" ) {
	$record["edit_link"] = false;
}
if( $data["Estado"]=="Pendiente" ) {
	if( now() >= $data['FechaMaxima'] )
		$record["css"]='background:#F5EE6C;';
}
if( $data["Estado"]=="En Proceso" )
	$record["css"]='background:#70F2FF;';
if( $data["Estado"]=="Terminado" )
	$record["css"]='background:#AFD562;';

;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Print page: Before SQL query
function BeforeQueryPrint(&$strSQL, &$strWhereClause, &$strOrderBy, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$strWhereClause = 'DepartamentoSolicitar = '.$_SESSION["CodigoDepto"];

;		
} // function BeforeQueryPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
if( $values['Estado'] == 'Pendiente' ) {
	if( $values['FechaAtencion'] < $values['FechaSolicitud'] || $values['FechaAtencion'] < $values['FechaInicio'] ) {
		$message = 'Fecha/Hora de Atencion debe ser mayor a Solicitud/Inicio, verifique...';
		return false;
	}
	$values['Estado'] = 'En Proceso';
} else if( $values['Estado'] == 'En Proceso' ) {
	$values['Estado'] = 'Terminado';
}
$values['Observaciones'] = mb_strtoupper($values['Observaciones']);
$values['ProcesoAtencion'] = mb_strtoupper($values['ProcesoAtencion']);

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
